version: 2.1

orbs:
    node: circleci/node@5.1.0
    release: fiveapp/release@0.0.3

executors:
    default:
        docker:
            - image: cimg/node:lts

jobs:
    test:
        executor: default
        steps:
            - checkout
            - node/install-packages
            - run: npm run lint
            - run: npm run test:json

workflows:
    build:
        jobs:
            - test
            - release/npm_and_github:
                context:
                    - org-global
                    - github-release
                requires:
                    - test
